---
- hosts: "linux10"
  become: true
  tasks:
  - name: instalamos apache
    package: 
      name: httpd
      state: latest
  - name: levantar servicio httpd y dejarlo persistente al reboot
    service:
      name: httpd
      state: started
      enabled: yes
  - name: creamos index.html
    file: 
      path: /var/www/html/index.html
      state: touch
  - name: añadimos contenido a index.html
    copy:
      content: "Hello World! jgarci41"
      dest: /var/www/html/index.html 